# Generated by Django 4.1.7 on 2023-02-21 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Oil Change", "Oil Change"),
                            ("Tire Rotation", "Tire Rotation"),
                            ("Brake Service", "Brake Service"),
                            ("Tune Up", "Tune Up"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("8:00 AM", "8:00 AM"),
                            ("8:30 AM", "8:30 AM"),
                            ("9:00 AM", "9:00 AM"),
                            ("9:30 AM", "9:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("1:00 PM", "1:00 PM"),
                            ("1:30 PM", "1:30 PM"),
                            ("2:00 PM", "2:00 PM"),
                            ("2:30 PM", "2:30 PM"),
                            ("3:00 PM", "3:00 PM"),
                            ("3:30 PM", "3:30 PM"),
                            ("4:00 PM", "4:00 PM"),
                            ("4:30 PM", "4:30 PM"),
                            ("5:00 PM", "5:00 PM"),
                        ],
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
