# Generated by Django 4.1.7 on 2023-02-21 23:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="date",
            new_name="day",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_ordered",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Oil Change", "Oil Change"),
                    ("Tire Rotation", "Tire Rotation"),
                    ("Brake Service", "Brake Service"),
                    ("Tune Up", "Tune Up"),
                    ("Other", "Other"),
                ],
                default="Doctor care",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00 AM", "8:00 AM"),
                    ("8:30 AM", "8:30 AM"),
                    ("9:00 AM", "9:00 AM"),
                    ("9:30 AM", "9:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("1:00 PM", "1:00 PM"),
                    ("1:30 PM", "1:30 PM"),
                    ("2:00 PM", "2:00 PM"),
                    ("2:30 PM", "2:30 PM"),
                    ("3:00 PM", "3:00 PM"),
                    ("3:30 PM", "3:30 PM"),
                    ("4:00 PM", "4:00 PM"),
                    ("4:30 PM", "4:30 PM"),
                    ("5:00 PM", "5:00 PM"),
                ],
                default="3 PM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
