# Generated by Django 4.1.7 on 2023-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookings",
            "0002_rename_date_appointment_day_remove_appointment_notes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("Oil Change", "Oil Change"),
                    ("Tire Rotation", "Tire Rotation"),
                    ("Brake Service", "Brake Service"),
                    ("Tune Up", "Tune Up"),
                    ("Other", "Other"),
                ],
                default="Oil Change",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00 AM", "8:00 AM"),
                    ("8:30 AM", "8:30 AM"),
                    ("9:00 AM", "9:00 AM"),
                    ("9:30 AM", "9:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("1:00 PM", "1:00 PM"),
                    ("1:30 PM", "1:30 PM"),
                    ("2:00 PM", "2:00 PM"),
                    ("2:30 PM", "2:30 PM"),
                    ("3:00 PM", "3:00 PM"),
                    ("3:30 PM", "3:30 PM"),
                    ("4:00 PM", "4:00 PM"),
                    ("4:30 PM", "4:30 PM"),
                    ("5:00 PM", "5:00 PM"),
                ],
                default="08:00 AM",
                max_length=10,
            ),
        ),
    ]
